version: '3.8'

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./festiflux:/app
  database:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=festiflux
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./local-database/init.sql:/docker-entrypoint-initdb.d/init.sql