version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./festiflux:/app
    command: bash -c "composer install && npm i && npm run dev && symfony server:start --no-tls --port=80"